# -*- coding: utf-8 -*-
"""assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dDyeGgFVQj8QKsnZGB_pu1LCzeM3qat6
"""

from scipy.stats import bernoulli
from scipy.stats import norm
from scipy.stats import binom
import random 
import array as event
import matplotlib.pyplot as plt
import math
import numpy as np

E_x=event.array('f',[0,0.5,2,2])
E_x2=event.array('f',[1,1/3,3,5])
for i in range(4):
  if E_x2 [i]- E_x[i]**2 < 0 :
    print(f'E[X]=',E_x[i],'E[X**2]=',E_x2[i],' cannot be attained')