# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lkiaturHh5je7ufUawKrBPGSejfG3Osy
"""

import numpy as np
# import uniform distribution
from scipy.stats import uniform
from matplotlib import pyplot as plt
import pandas as pd



x1=[0,1]
y1=[0,0.5]
x2=[1,2]
y2=[0.6,0.6]
x3=[2,3]
y3=[0.75,0.875]
x4=[3,4]
y4=[1,1]
plt.plot(x1,y1)
plt.plot(x2,y2)
plt.plot(x3,y3)
plt.plot(x4,y4)
plt.xlabel("X")
plt.ylabel("F(x)")
plt.title("Cumulative distribution function")

plt.show()