# -*- coding: utf-8 -*-
"""assign2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UtAGwdwNSqxtSTehvFchAY0GOqu4SPS8
"""

import numpy as np
# import uniform distribution
from scipy.stats import uniform
from matplotlib import pyplot as plt
import pandas as pd

def cdf(x):
  if x < 0:
    f_x = 0
  elif x < 1:
    f_x = x/2
  elif x<2:
    f_x = 0.6
  elif x<3:
    f_x = 0.5 + x/8
  else:
    f_x = 1
  return f_x

vcdf=np.vectorize(cdf)
x=np.linspace(0,5)
y=vcdf(x)
plt.plot(x,y)
plt.xlabel("X")
plt.ylabel("F(x)")
plt.title("Cumulative distribution function")
plt.grid(b=True)
plt.show()